### ISSUE TITLE
Errors when running xmip tutorial notebook 

### ISSUE THREAD

**Issue by briochemc** [coecms/xmip_nci#1]
I just ran the [xmip tutorial notebook](https://github.com/coecms/xmip_nci/blob/main/xmip_tutorial.ipynb) on Gadi today and got most things working but not everything, so here are the problems I encountered. Hopefully you can help me figure how to resolve them and this is helpful to others too! 😃 

- Inconsistent time types do not seem to be dealt with by default anymore (I used the latest environment, `analysis3-24.04`), so I had to include `xarray_open_kwargs={'use_cftime': True}` (as per https://github.com/intake/intake-esm/discussions/561#discussioncomment-4753117) in each `to_dataset_dict` call, i.e., use
    ```python
    subset.to_dataset_dict(xarray_open_kwargs={'use_cftime': True}, ...)
    ```
    I can quickly submit a PR for that fix if you want me to: Just let me know.

- As is the case in the notebook saved here, the penultimate cell, which is supposed to load a bunch of models to apply preprocessing, only seems to find ACCESS-ESM1.5 when matching the query:

    <img width="80%" alt="Screenshot 2024-05-15 at 11 58 57 AM" src="https://github.com/coecms/xmip_nci/assets/4486578/012131fe-de83-40bd-89d8-b51cb8a35947">
 
    (It should find runs for every model according to the original tutorial.) Given that the original tuotiral uses the PANGEO catalog, could it just be that these files were not cataloged on NCI? I'm no expert here so I don't know. Or maybe it has to do with the NCI config of intake? Any idea how to fix this?

- Another issue with the penultimate cell (also the case in the notebook saved here) is that it errors on finding the files corresponding to the ACCESS-ESM1.5 data:

    ```ipynb
    OSError: 
            Failed to open netCDF/HDF dataset.

            *** Arguments passed to xarray.open_dataset() ***:

            - filename_or_obj: /g/data/fs38/publications/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r38i1p1f1/Oyr/o2/gn/v20210525/o2_Oyr_ACCESS-ESM1-5_historical_r38i1p1f1_gn_2000-2014.nc
            - kwargs: {'chunks': {}}

            *** fsspec options used ***:

            - root: /g/data/fs38/publications/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r38i1p1f1/Oyr/o2/gn/v20210525/o2_Oyr_ACCESS-ESM1-5_historical_r38i1p1f1_gn_2000-2014.nc
            - protocol: None

            ********************************************
    ```

    I think the issue here may be that intake does not deal well with links to other files? FWIW this is the link:
    ```unix
    ../files/d20200529/o2_Oyr_ACCESS-ESM1-5_historical_r8i1p1f1_gn_1950-2014.nc
    ```
    Any idea how to fix this error?

**Comment by briochemc** [comment]
Gentle ping @paolap in case you can take a look at this notebook and update it to work with the current NCI catalogs. Please let me know if you'd like me to run/test anything in particular :)

**Comment by paolap** [comment]
Hi Benoit,

apologies for the long wait, I fixed the cftime issue. 
For the second question, this is using our old intake catalogue which we aren't updating anymore. As CLEX will be wrapping up soon it's getting increasingly difficult to decide what to update, discard etc. We stopped updating the intake catalogue as now there's an NCI equivalent. I will try to switch this tutorial to that catalogue, however, the purpose of this notebook is to give a demo of the tool, in a way it's irrelevant that it can't find all these models, it just means they weren't available when we stopped updating. However, we will probably remove the catalogue completely, so it might still be helpful to get this working with the official NCI catalogue.

**Comment by paolap** [comment]
Actually, I was wrong, ACCESS-ESM1.5 it's the only available dataset even in the new catalogue, I will look for a different variable that ight be more popular, I nearly have the example with the enw catalogue ready, the irony is NCI catalogues split ACCESS data and replicated data in two different catalogues so now the last example doesn't return anything!

**Comment by paolap** [comment]
Ok, I now have a NCI catalogue version, you can still use it with hh5 env but you also need to be part of dk92 to get direct access to their catalogue

**Comment by briochemc** [comment]
Thank you very much for looking into this!
